pace/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'pace'

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^login/', views.LoginUserView.as_view(), name='login'),
    url(r'^logout/', auth_views.LogoutView.as_view(template_name='pace/logout.html'), name='logout'),
    url(r'^dashboard/', views.DashboardView.as_view(), name='dashboard'),
    url(r'^sign_up/', views.SignUpView.as_view(), name='sign_up'),
    url(r'^session_list/', views.SessionListView.as_view(), name='session_list'),
    url(r'^activity_list/', views.ActivityListView.as_view(), name='activity_list'),
    url(r'^progress/', views.ProgressView.as_view(), name='progress'),
    url(r'^add_activity/(?P<pk>\d+)/$', views.AddActivityView.as_view(), name='add_activity'),
    url(r'^add_session', views.AddSessionView.as_view(), name='add_session'),
]

paceProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('pace.urls')),
    url(r'^admin/', admin.site.urls),
]

pace/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib import auth
from django import forms

# Create your models here.
ACTIVITY_CHOICES = {
  ('Choose Activity', 'Choose Activity'),
  ('Running', 'Running'),
  ('Walking', 'Walking'),
  ('Weight-lifting', 'Weight-lifting'),
  ('Push-ups', 'Push-ups'),
  ('Sit-ups', 'Sit-ups'),
}

User = auth.get_user_model()

class PaceUser(auth.models.User, auth.models.PermissionsMixin):
    def __str__(self):
        return self.username

class Session(models.Model):
    session_length = models.PositiveIntegerField(default=0, blank=True, null=True)
    date = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse("pace:session_list")

class Activity(models.Model):
    name= models.CharField(max_length=256, choices=ACTIVITY_CHOICES, default='Choose Activity')
    activity_type = models.CharField(max_length=256)
    hours = models.PositiveIntegerField(default=0)
    minutes = models.PositiveIntegerField(default=0)
    reps = models.PositiveIntegerField(default=0)
    session = models.ForeignKey(Session, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("pace:session_list")

pace/forms.py
from django import forms
from pace.models import Activity, Session
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class DateInput(forms.DateInput):
    input_type = 'date'

class UserCreateForm(UserCreationForm):
    class Meta:
        model= get_user_model()
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Username'
        self.fields['email'].label = 'Email'
        self.fields['password2'].label = 'Confirm Password'
        self.fields['username'].widget.attrs.update(
          {'class' : 'form-control input-field', 'placeholder': 'username'})
        self.fields['email'].widget.attrs.update(
          {'class' : 'form-control input-field', 'placeholder': 'email'})
        self.fields['password1'].widget.attrs.update(
          {'class' : 'form-control input-field', 'placeholder': 'password'})
        self.fields['password2'].widget.attrs.update(
          {'class' : 'form-control input-field', 'placeholder': 'confirm password'})

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Username'
        self.fields['username'].widget.attrs.update(
          {'class' : 'form-control input-field', 'placeholder': 'username'})
        self.fields['password'].widget.attrs.update(
          {'class' : 'form-control input-field', 'placeholder': 'password'})

class AddActivityForm(forms.ModelForm):
    class Meta:
        fields = ("name", "hours", "minutes")
        model = Activity

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].label = 'Name of Activity'
        self.fields['hours'].label = 'Number of Hours'
        self.fields['hours'].widget.attrs.update(
          {'class' : 'form-control input-field', 'placeholder': 'duration'})
        self.fields['minutes'].label = 'Number of Minutes'
        self.fields['minutes'].widget.attrs.update(
          {'class' : 'form-control input-field', 'placeholder': 'duration'})

class AddSessionForm(forms.ModelForm):
    class Meta:
        fields = ("date",)
        model = Session
        widgets = {
          'date': DateInput()
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

pace/views.py
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from pace.forms import UserCreateForm, UserLoginForm, AddActivityForm, AddSessionForm
from pace.models import Session, Activity
from django.views.generic import (TemplateView, DetailView, FormView, ListView, CreateView, DeleteView, UpdateView)


# Create your views here.
class HomeView(TemplateView):
    template_name = 'home.html'

class LoginUserView(LoginView):
    template_name='login.html'
    form_class = UserLoginForm

class SignUpView(CreateView):
    context_object_name= 'user_create'
    success_url = reverse_lazy('pace:login')
    form_class = UserCreateForm
    template_name='sign_up.html'

class DashboardView(LoginRequiredMixin,TemplateView):
    template_name='dashboard.html'

class SessionListView(ListView):
    model = Session
    template_name='session_list.html'

    def get_queryset(self):
        return Session.objects.filter(user=self.request.user.id)

class ActivityListView(ListView):
    model = Activity
    template_name='activity_list.html'

   # def get_queryset(self):
    #    return Activity.objects.filter(session=self.session.id)

class ProgressView(DetailView):
    template_name='progress.html'

class AddActivityView(CreateView):
    model = Activity
    template_name='add_activity.html'
    form_class = AddActivityForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.session = Session.objects.get(id=self.kwargs['pk'])
        self.object.save()
        return super().form_valid(form)

class AddSessionView(CreateView):
    model = Session
    template_name='add_session.html'
    form_class = AddSessionForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

pace/templates/pace/activity_list.html
{% block content %}
  {% for activity in activity_list %}
    <div class="activity-card">
    <h4>{{activity.name}}</h4>
    <h4>Duration: {{activity.hours}}:{{activity.minutes}}</h4>
    </div>
  {% endfor %}
{% endblock %}

pace/templates/pace/add_activity.html
{% extends "pace/base.html" %}
{% block content %}
<h1 class="page-title">Add Activity</h1>
<form class="flex-parent flex-parent-small-margin" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input class="simple-button" type="submit" value="Add">
</form>
{% endblock %}

pace/templates/pace/add_session.html
{% extends "pace/base.html" %}
{% block content %}
<h1 class="page-title">Add Session</h1>
<form class="flex-parent flex-parent-small-margin" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input class="simple-button" type="submit" value="Add">
</form>
{% endblock %}

pace/templates/pace/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <title>Pace</title>
    <link rel='stylesheet' href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel='stylesheet' href="{% static 'css/page.css' %}">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p|Ubuntu:700,700i" rel="stylesheet">
  <style>
    * {
        vertical-align: baseline;
        font-weight: inherit;
        font-family: inherit;
        font-style: inherit;
        font-size: 100%;
        border: 0 none;
        outline: 0;
        padding: 0;
        margin: 0;
        box-sizing: border-box;
    }

    h1,h2 {
        color:black;
    }

    a {
        color:white;
    }

    a:hover {
      color:white;
    }

    body {
      padding: 0px;
    }


    li, dd, blockquote {
     margin-left: 40px;
    }

    table {
    border-collapse: collapse;
    border-spacing: 0;
    }
    </style>
  </head>
<body>
<nav class="navbar">
  <ul>
    {% if user.is_authenticated %}
        <li class="icon" id="icon"><img src="{% static 'media/logo.png' %}" alt="logo" /></li>
        <li><a href="{% url 'pace:logout' %}"><button class="landing-button">Sign out</button></a></li>
    {% else %}
        <li class="icon" id="icon"><img src="{% static 'media/logo.png' %}" alt="logo" /></li>
        <li><a href="{% url 'pace:login' %}"><button class="landing-button">Sign In</button></a></li>
        <li><a href="{% url 'pace:sign_up' %}"><button class="landing-button">Create Account</button></a></li>
    {% endif %}
  </ul>
</nav>
<div></div>
{% block content %}
{% endblock %}

</body>
</html>

pace/templates/pace/dashboard.html
{% extends "pace/base.html" %}
{% load staticfiles %}
{% block content %}
<main class="flex-parent flex-parent-large-margin">
    <a href="{% url 'pace:session_list' %}"><button>View Sessions</button></a>
    <a href="{% url 'pace:progress' %}"><button> View Progress</button></a>
</main>
{% endblock %}

pace/templates/pace/home.html
{% extends "pace/base.html" %}
{% load staticfiles %}
{% block content %}
<div class="landing-body">
<main class="landing-titles">
  <div class="titles">
    <h1>Welcome to Pace</h1>
    <h2>Track Your Progress</h2>
    <h2>And Get In Shape</h2>
    <br/>
    <button class="landing-button">Get Started</button>
  </div>
</main>
</div>
<div class="image-landing">
</div>
{% endblock %}

pace/templates/pace/login.html
{% extends "pace/base.html" %}
{% block content %}
<h1 class="page-title">Log In With Your Username</h1>
<form class="flex-parent flex-parent-small-margin" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input class="simple-button" type="submit" value="Log in" />
</form>
{% endblock %}

pace/templates/pace/progress.html
{% extends "pace/base.html" %}
{% block content %}
<h1>progress</h1>
{% endblock %}

pace/templates/pace/session_list.html
{% extends "pace/base.html" %}
{% block content %}
  <h1 class="session-title">Your Sessions</h1>
{% for session in session_list %}
<div class="session-card">
  <h2>Session for: {{ session.date }}</h2>
  {% include "pace/activity_list.html" with activity_list=session.activity_set.all %}
  <a href="{% url 'pace:add_activity' pk=session.pk %}"><button class="add-activity-button">+ Add Activity</button></a>
</div>
{% endfor %}
  <a href="{% url 'pace:add_session' %}"><button class="add-session-button">+ Add Session</button></a>
{% endblock %}

pace/templates/pace/sign_up.html
{% extends "pace/base.html" %}
{% block content %}
<h1 class="page-title">Create Your Account</h1>
<form class="flex-parent flex-parent-small-margin" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input class="simple-button" type="submit" value="Sign Up">
</form>
{% endblock %}